name: flutter_gstreamer_player
description: A GStreamer-powered alternative to Flutter's video_player that support Linux, iOS and Android.
version: 0.0.3
homepage: https://github.com/hpdragon1618/flutter_gstreamer_player

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hpdragon1618.flutter_gstreamer_player
        pluginClass: FlutterGstreamerPlayerPlugin
